apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openaire-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/the-alien-club/datastreaming-demos.git
    targetRevision: main
    path: openaire/helm/openaire-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: openaire

  # Track only, no automatic sync
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
