services:
  openaire:
    build:
      context: .
      dockerfile: Dockerfile
    image: rg.fr-par.scw.cloud/ns-data-streaming/demo-openaire:0.1.6
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LOG_LEVEL=info
    stdin_open: true
    tty: true
    restart: unless-stopped
